[package]
name = "obs-livesplit-one"
version = "0.1.0"
authors = ["Christopher Serr <christopher.serr@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["obs"]

[lib]
crate-type = ["cdylib"]

[dependencies]
livesplit-core = { git = "https://github.com/LiveSplit/livesplit-core", features = ["software-rendering", "font-loading"] }
once_cell = "1.5.2"

[profile.dev.package."*"]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false

[profile.dev.build-override]
opt-level = 0

[profile.release]
lto = true
panic = "abort"

[profile.release.build-override]
opt-level = 0
